type: matching
custom_name: When are the exceptions raised?
captions:
- SyntaxError
- ValueError
- OSError
- NameError
options:
- No such variable in your program.
- Tried to enter your name when an integer was expected.
- "Deleted the file from a directory, and the code can't reach it."
- Forgot to type the closing bracket of a list.
files:
- name: main.py
  visible: true
  text: |+
    #  You can experiment here, it wonâ€™t be checked

  learner_created: false
feedback_link: https://hyperskill.org/learn/step/11683#comment
status: Solved
record: -1
ordering:
- 0
- 1
- 2
- 3
